// const px = (id) =>
//   `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1100&w=800`;

// const shop = (platform, q) => {
//   const query = encodeURIComponent(q);
//   if (platform === "amazon") return `https://www.amazon.in/s?k=${query}`;
//   if (platform === "flipkart")
//     return `https://www.flipkart.com/search?q=${query}`;
//   if (platform === "meesho") return `https://www.meesho.com/search?q=${query}`;
//   return `https://www.myntra.com/${query}`;
// };

// const links = (q, price) => [
//   { platform: "amazon", url: shop("amazon", `${q} amazon`), price: price },
//   { platform: "flipkart", url: shop("flipkart", q), price: price - 30 },
//   { platform: "meesho", url: shop("meesho", q), price: price - 70 },
//   { platform: "myntra", url: shop("myntra", q), price: price + 50 },
// ];

// const T = ["S", "M", "L", "XL", "XXL"];
// const K = ["S", "M", "L", "XL", "XXL", "3XL"];

export const seedProducts = [];

// export const seedProducts = [
//   {
//     name: "Everyday Cotton Tee — Cloud White",
//     slug: "vimuhet-everyday-cotton-tee-cloud-white",
//     category: "tshirts",
//     tagline: "240 GSM combed cotton, zero-shrink finish",
//     description:
//       "The tee we wear on repeat. Cut from 240 GSM bio-washed combed cotton with a reinforced shoulder tape and a clean ribbed neck that keeps its shape wash after wash. Pre-shrunk, enzyme washed and dyed in small batches for a colour that stays true.",
//     fabric: "100% combed cotton, 240 GSM",
//     fit: "Regular",
//     care: "Machine wash cold, do not bleach, warm iron inside out",
//     price: 549,
//     originalPrice: 1299,
//     sizes: T,
//     colors: ["Cloud White", "Ink Black"],
//     images: [px(18257675), px(20669538), px(14867670)],
//     links: links("vimuhet white cotton tshirt", 549),
//     badge: "Bestseller",
//     featured: true,
//     rating: 48,
//     sortOrder: 1,
//   },
//   {
//     name: "Sunset Orange Oversized Tee",
//     slug: "vimuhet-sunset-orange-oversized-tee",
//     category: "tshirts",
//     tagline: "Drop-shoulder street fit",
//     description:
//       "A saturated sunset orange with a relaxed drop-shoulder silhouette and a boxy hem. Garment dyed for that lived-in softness from day one.",
//     fabric: "Heavyweight cotton jersey, 220 GSM",
//     fit: "Oversized",
//     care: "Machine wash cold with like colours",
//     price: 649,
//     originalPrice: 1499,
//     sizes: T,
//     colors: ["Sunset Orange"],
//     images: [px(8148577), px(36392069)],
//     links: links("vimuhet oversized tshirt orange", 649),
//     badge: "New Drop",
//     featured: true,
//     rating: 47,
//     sortOrder: 2,
//   },
//   {
//     name: "Blush Pink Full-Sleeve Tee",
//     slug: "vimuhet-blush-pink-full-sleeve-tee",
//     category: "tshirts",
//     tagline: "Soft-touch interlock, layer-ready",
//     description:
//       "Blush pink interlock cotton with a slim-but-easy body. Layers under everything and looks just as good on its own.",
//     fabric: "Cotton interlock, 200 GSM",
//     fit: "Slim",
//     care: "Machine wash cold, tumble dry low",
//     price: 699,
//     originalPrice: 1599,
//     sizes: T,
//     colors: ["Blush Pink"],
//     images: [px(9558699), px(9558761)],
//     links: links("vimuhet full sleeve tshirt pink", 699),
//     badge: "",
//     featured: false,
//     rating: 46,
//     sortOrder: 3,
//   },
//   {
//     name: "Sage Lounge Tee — Pack of 2",
//     slug: "vimuhet-sage-lounge-tee-pack-of-2",
//     category: "tshirts",
//     tagline: "Two tees, one calm palette",
//     description:
//       "A value pack built for the weekend. One sage green, one off-white, both in airy single jersey that breathes through Indian summers.",
//     fabric: "Cotton rich single jersey, 180 GSM",
//     fit: "Relaxed",
//     care: "Machine wash cold",
//     price: 999,
//     originalPrice: 2299,
//     sizes: T,
//     colors: ["Sage", "Off White"],
//     images: [px(26563051)],
//     links: links("vimuhet tshirt pack of 2", 999),
//     badge: "Value Pack",
//     featured: false,
//     rating: 45,
//     sortOrder: 4,
//   },
//   {
//     name: "Midnight Navy Fleece Hoodie",
//     slug: "vimuhet-midnight-navy-fleece-hoodie",
//     category: "hoodies",
//     tagline: "Brushed inside, structured outside",
//     description:
//       "Loop-back brushed fleece with a double-layer hood, metal-tipped drawcords and a kangaroo pocket deep enough for everything.",
//     fabric: "Cotton-rich brushed fleece, 320 GSM",
//     fit: "Regular",
//     care: "Wash inside out, do not iron on print",
//     price: 1499,
//     originalPrice: 2999,
//     sizes: T,
//     colors: ["Midnight Navy"],
//     images: [px(19461567), px(28701950)],
//     links: links("vimuhet navy hoodie", 1499),
//     badge: "Bestseller",
//     featured: true,
//     rating: 49,
//     sortOrder: 5,
//   },
//   {
//     name: "Cloud Fleece White Hoodie",
//     slug: "vimuhet-cloud-fleece-white-hoodie",
//     category: "hoodies",
//     tagline: "Off-white, off-duty",
//     description:
//       "A clean off-white hoodie with tonal stitching and a boxy fit. The one you grab for airport runs and late-night chai.",
//     fabric: "Loop-back cotton fleece, 300 GSM",
//     fit: "Boxy",
//     care: "Machine wash cold, dry in shade",
//     price: 1399,
//     originalPrice: 2799,
//     sizes: T,
//     colors: ["Cloud White"],
//     images: [px(8217415), px(6612171)],
//     links: links("vimuhet white hoodie", 1399),
//     badge: "",
//     featured: false,
//     rating: 47,
//     sortOrder: 6,
//   },
//   {
//     name: "Neon Nights Cropped Hoodie",
//     slug: "vimuhet-neon-nights-cropped-hoodie",
//     category: "hoodies",
//     tagline: "Cropped, cropped, cropped",
//     description:
//       "Neon-lit studio energy in a cropped body with ribbed hem. Designed for layering over high-rise everything.",
//     fabric: "Cotton poly fleece, 280 GSM",
//     fit: "Cropped",
//     care: "Hand wash recommended",
//     price: 1299,
//     originalPrice: 2599,
//     sizes: ["XS", "S", "M", "L", "XL"],
//     colors: ["Neon Pink"],
//     images: [px(9998657), px(2373539)],
//     links: links("vimuhet crop hoodie women", 1299),
//     badge: "Trending",
//     featured: true,
//     rating: 48,
//     sortOrder: 7,
//   },
//   {
//     name: "Ember Orange Studio Hoodie",
//     slug: "vimuhet-ember-orange-studio-hoodie",
//     category: "hoodies",
//     tagline: "The loudest piece in the rack",
//     description:
//       "Ember orange fleece with a high-neck hood and hidden thumbholes. Cut long in the body with dropped shoulders.",
//     fabric: "Heavy fleece, 330 GSM",
//     fit: "Oversized",
//     care: "Machine wash cold",
//     price: 1549,
//     originalPrice: 3099,
//     sizes: T,
//     colors: ["Ember Orange"],
//     images: [px(30720840), px(30720843)],
//     links: links("vimuhet orange hoodie", 1549),
//     badge: "Limited",
//     featured: false,
//     rating: 46,
//     sortOrder: 8,
//   },
//   {
//     name: "Rose Pink Chikankari Kurta",
//     slug: "vimuhet-rose-pink-chikankari-kurta",
//     category: "kurtas",
//     tagline: "Hand-shadow work on soft mul",
//     description:
//       "Feather-light mul cotton with hand-guided chikankari shadow work along the yoke. Side slits, straight silhouette, pockets inside.",
//     fabric: "Mul cotton with cotton thread embroidery",
//     fit: "Straight",
//     care: "Gentle hand wash separately",
//     price: 1199,
//     originalPrice: 2499,
//     sizes: K,
//     colors: ["Rose Pink"],
//     images: [px(35445207), px(12279088)],
//     links: links("vimuhet chikankari kurta pink", 1199),
//     badge: "Handwork",
//     featured: true,
//     rating: 49,
//     sortOrder: 9,
//   },
//   {
//     name: "Marigold Thread-Work Kurta Set",
//     slug: "vimuhet-marigold-thread-work-kurta-set",
//     category: "kurtas",
//     tagline: "Kurta + pant, festive ready",
//     description:
//       "Marigold yellow with tonal thread embroidery on the neckline, sold as a set with tapered pants. Made for haldi mornings and late evenings.",
//     fabric: "Silk-blend with viscose lining",
//     fit: "A-line",
//     care: "Dry clean recommended",
//     price: 1899,
//     originalPrice: 3599,
//     sizes: K,
//     colors: ["Marigold"],
//     images: [px(18878869), px(8771006)],
//     links: links("vimuhet kurta set yellow", 1899),
//     badge: "Festive",
//     featured: true,
//     rating: 48,
//     sortOrder: 10,
//   },
//   {
//     name: "Scarlet Floral Straight Kurta",
//     slug: "vimuhet-scarlet-floral-straight-kurta",
//     category: "kurtas",
//     tagline: "Everyday ethnic, elevated",
//     description:
//       "A scarlet floral print that works from desk to dinner, with three-quarter sleeves and a curved hem.",
//     fabric: "Rayon blend print",
//     fit: "Straight",
//     care: "Machine wash gentle",
//     price: 1099,
//     originalPrice: 2299,
//     sizes: K,
//     colors: ["Scarlet"],
//     images: [px(35504991), px(7792218)],
//     links: links("vimuhet floral kurta red", 1099),
//     badge: "",
//     featured: false,
//     rating: 45,
//     sortOrder: 11,
//   },
//   {
//     name: "Festive Maroon Pathani Suit",
//     slug: "vimuhet-festive-maroon-pathani-suit",
//     category: "kurtas",
//     tagline: "Structured, celebratory, timeless",
//     description:
//       "Deep maroon pathani with a mandarin collar, double pockets and a matching pyjama. Tailored through the shoulder for a sharp line.",
//     fabric: "Cotton silk blend",
//     fit: "Tailored",
//     care: "Dry clean only",
//     price: 1699,
//     originalPrice: 3299,
//     sizes: K,
//     colors: ["Maroon"],
//     images: [px(9020697)],
//     links: links("vimuhet pathani suit maroon", 1699),
//     badge: "Wedding Edit",
//     featured: false,
//     rating: 47,
//     sortOrder: 12,
//   },
//   {
//     name: "Editorial Overshirt — Sequin Flash",
//     slug: "vimuhet-editorial-overshirt-sequin-flash",
//     category: "shirts",
//     tagline: "Party-layer with a shout",
//     description:
//       "A statement overshirt with sequin-embellished panels over matte twill. Wear open over a tee or buttoned up with black denim.",
//     fabric: "Poly twill with sequin panelling",
//     fit: "Relaxed",
//     care: "Dry clean only",
//     price: 1249,
//     originalPrice: 2499,
//     sizes: T,
//     colors: ["Chartreuse"],
//     images: [px(10330187)],
//     links: links("vimuhet sequin overshirt", 1249),
//     badge: "Party",
//     featured: false,
//     rating: 44,
//     sortOrder: 13,
//   },
//   {
//     name: "Boutique Linen Shirt",
//     slug: "vimuhet-boutique-linen-shirt",
//     category: "shirts",
//     tagline: "Breezy pure linen, camp collar",
//     description:
//       "Pure linen with a soft camp collar and a relaxed body. The answer to every humid Friday.",
//     fabric: "100% linen, 120 GSM",
//     fit: "Relaxed",
//     care: "Machine wash cold, line dry",
//     price: 1149,
//     originalPrice: 2299,
//     sizes: T,
//     colors: ["Sand", "Cream"],
//     images: [px(13532891), px(8581033), px(35045845)],
//     links: links("vimuhet linen shirt", 1149),
//     badge: "Summer",
//     featured: false,
//     rating: 46,
//     sortOrder: 14,
//   },
//   {
//     name: "Sunflower Tiered Maxi Dress",
//     slug: "vimuhet-sunflower-tiered-maxi-dress",
//     category: "dresses",
//     tagline: "Swish-worthy tiers",
//     description:
//       "Three tiers, one very happy silhouette. Sunflower yellow georgette with a smocked bodice and adjustable straps.",
//     fabric: "Georgette with cotton lining",
//     fit: "Flared",
//     care: "Hand wash separately",
//     price: 1349,
//     originalPrice: 2799,
//     sizes: ["XS", "S", "M", "L", "XL"],
//     colors: ["Sunflower"],
//     images: [px(8771006), px(9246697)],
//     links: links("vimuhet yellow maxi dress", 1349),
//     badge: "New Drop",
//     featured: true,
//     rating: 47,
//     sortOrder: 15,
//   },
// ];
